version: '3.2'
services:
  kbs:
    image: ghcr.io/confidential-containers/key-broker-service:v0.7.0
    container_name: key-broker-service
    command: [
        "/usr/local/bin/kbs",
        "--private-key",
        "/opt/confidential-containers/kbs/server.key",
        "--certificate",
        "/opt/confidential-containers/kbs/server.crt",
        "--socket",
        "0.0.0.0:8080",
        "--config",
        "/etc/kbs-config.json",
        "--auth-public-key",
        "/opt/confidential-containers/kbs/user-keys/public.pub",
      ]
    restart: always # keep the server running
    ports:
      - "8080:8080"
    volumes:
      - ./data/server.key:/opt/confidential-containers/kbs/server.key
      - ./data/server.crt:/opt/confidential-containers/kbs/server.crt
      - ./data/repository:/opt/confidential-containers/kbs/repository:rw
      - ./data/public.pub:/opt/confidential-containers/kbs/user-keys/public.pub
      - ./configs/kbs-config.json:/etc/kbs-config.json

  as:
    image: xinjian1326/attestation-service:latest
    container_name: attestation-service
    ports:
    - "50003:50003"
    restart: always
    volumes:
      - ./data/attestation-service:/opt/confidential-containers/attestation-service:rw
      - ./configs/as-config.json:/etc/as-config.json:rw
      - ./configs/sgx_default_qcnl.conf:/etc/sgx_default_qcnl.conf:rw
    environment:
      - RUST_LOG=debug
    command: [
      "grpc-as",
      "--socket",
      "0.0.0.0:50003",
      "--rvps-address",
      "http://rvps:50004",
      "--config",
      "/etc/as-config.json"
    ]

  rvps:
    image: ghcr.io/confidential-containers/reference-value-provider-service:v0.7.0
    container_name: rvps
    command: [
        "/usr/local/bin/rvps",
        "--socket",
        "0.0.0.0:50004",
      ]
    restart: always # keep the server running
    ports:
      - "50004:50004"
    volumes:
      - ./data/attestation-service/reference-values:/opt/confidential-containers/attestation-service/reference_values:rw
